global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_fast"
    scrape_interval: 2s
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "node_slow"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9200"]